In [1]:
import pandas as pd
#original file had to be deleted
df = pd.read_csv('Resources/Parking_Violations_Issued_-_Fiscal_Year_2023.csv')

C:\Users\choju\AppData\Roaming\Python\Python37\site-packages\IPython\core\interactiveshell.py:3553: DtypeWarning: Columns (17,18,20,22,23,29,30,31,32,36,38) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [2]:
pd.set_option('display.max_columns', None)
df.head(10)

,Summons Number,Plate ID,Registration State,Plate Type,Issue Date,Violation Code,Vehicle Body Type,Vehicle Make,Issuing Agency,Street Code1,Street Code2,Street Code3,Vehicle Expiration Date,Violation Location,Violation Precinct,Issuer Precinct,Issuer Code,Issuer Command,Issuer Squad,Violation Time,Time First Observed,Violation County,Violation In Front Of Or Opposite,House Number,Street Name,Intersecting Street,Date First Observed,Law Section,Sub Division,Violation Legal Code,Days Parking In Effect,From Hours In Effect,To Hours In Effect,Vehicle Color,Unregistered Vehicle?,Vehicle Year,Meter Number,Feet From Curb,Violation Post Code,Violation Description,No Standing or Stopping Violation,Hydrant Violation,Double Parking Violation
0,1484697303,JER1863,NY,PAS,06/10/2022,67,SDN,TOYOT,P,34330,179,0,20221210,10.0,10,1,160195,0001,0.0,1037A,NaN,NY,F,NaN,W 28TH ST,CHELSEA PK,0,408,E3,NaN,BBBBBBB,ALL,ALL,BLK,0.0,2004,-,0,NaN,NaN,NaN,NaN,NaN
1,1484697315,KEV4487,NY,PAS,06/13/2022,51,SUBN,JEEP,K,34310,16400,11010,20220908,10.0,10,1,160195,0001,0.0,1045A,NaN,NY,O,436,27TH DR,NaN,0,408,F3,NaN,BBBBBBB,ALL,ALL,GRAY,0.0,2017,-,0,NaN,NaN,NaN,NaN,NaN
2,1484697625,H73NYD,NJ,PAS,06/19/2022,63,SDN,JEEP,N,30640,13015,28540,0,1.0,1,1,161315,0001,0.0,1116A,NaN,NY,NaN,109,SOUTH ST,NaN,0,408,F3,NaN,BBBBBBB,ALL,ALL,GRAY,0.0,0,-,0,NaN,NaN,NaN,NaN,NaN
3,1484697674,GJC9296,NY,PAS,06/19/2022,63,SUBN,LEXUS,N,30640,13015,28540,20230820,1.0,1,1,161315,0001,0.0,1052A,NaN,NY,NaN,109,SOUTH ST,NaN,0,408,F3,NaN,BBBBBBB,ALL,ALL,NaN,0.0,0,-,0,NaN,NaN,NaN,NaN,NaN
4,1484697686,M51PUV,NJ,PAS,06/19/2022,63,SDN,HYUND,N,30640,13015,28540,0,1.0,1,1,161315,0001,0.0,1107A,NaN,NY,NaN,109,SOUTH ST,NaN,0,408,F3,NaN,BBBBBBB,ALL,ALL,BLUE,0.0,0,-,0,NaN,NaN,NaN,NaN,NaN
5,1484697698,H73NYD,NJ,PAS,06/23/2022,63,NaN,JEEP,K,30640,13015,28540,0,1.0,1,1,161315,0001,0.0,1050A,NaN,NY,O,109,SOUTH ST,NaN,0,408,E3,NaN,BBBBBBB,ALL,ALL,NaN,0.0,0,-,0,NaN,NaN,NaN,NaN,NaN
6,1484697728,M51PUV,NJ,PAS,06/23/2022,63,NaN,HYUND,K,30640,13015,28540,0,1.0,1,1,161315,0001,0.0,1101A,NaN,NY,O,109,SOUTH ST,NaN,0,408,F3,NaN,BBBBBBB,ALL,ALL,BLUE,0.0,0,-,0,NaN,NaN,NaN,NaN,NaN
7,1484698204,KJJ8637,NY,PAS,06/20/2022,67,SUBN,TOYOT,N,11585,26390,15010,20230120,5.0,5,1,160954,0001,0.0,1205P,NaN,NY,F,NaN,COLEMAN PLAYGROUND,NaN,0,408,E3,NaN,BBBBBBB,ALL,ALL,WHITE,0.0,2021,-,0,NaN,NaN,NaN,NaN,NaN
8,1484698381,JEC8631,NY,PAS,06/19/2022,98,SUBN,NISSA,N,0,0,0,20230121,10.0,10,1,161348,0001,0.0,0535P,NaN,NY,NaN,NaN,S/S W 28TH STREET,W/O 9TH AVENUE,0,408,B,NaN,BBBBBBB,ALL,ALL,BLK,0.0,2002,-,0,NaN,NaN,NaN,NaN,NaN
9,1484698721,K21PNH,NJ,PAS,06/25/2022,10,SUBN,JEEP,K,33190,25190,31990,0,6.0,6,1,161134,0001,0.0,0307P,NaN,NY,O,40,WASHINGTON SQ SO,NaN,0,408,B,NaN,BBBBBBB,ALL,ALL,RED,0.0,0,-,0,NaN,NaN,NaN,NaN,NaN

In [3]:
len(df.index)

10224823

In [4]:
df.isna().sum()

Summons Number                              0
Plate ID                                  106
Registration State                          0
Plate Type                                  0
Issue Date                                  0
Violation Code                              0
Vehicle Body Type                       24588
Vehicle Make                             9569
Issuing Agency                              0
Street Code1                                0
Street Code2                                0
Street Code3                                0
Vehicle Expiration Date                     0
Violation Location                    4799416
Violation Precinct                          0
Issuer Precinct                             0
Issuer Code                                 0
Issuer Command                        4794498
Issuer Squad                          5147300
Violation Time                            108
Time First Observed                   9650471
Violation County                        28414
Violation In Front Of Or Opposite     4848362
House Number                          4885709
Street Name                              1167
Intersecting Street                   4710633
Date First Observed                         0
Law Section                                 0
Sub Division                             1507
Violation Legal Code                  5430323
Days Parking In Effect                4883419
From Hours In Effect                  7098254
To Hours In Effect                    7098265
Vehicle Color                          921029
Unregistered Vehicle?                10010848
Vehicle Year                                0
Meter Number                          9099206
Feet From Curb                              0
Violation Post Code                   5361242
Violation Description                  214522
No Standing or Stopping Violation    10224823
Hydrant Violation                    10224823
Double Parking Violation             10224823
dtype: int64

In [5]:
dropped_df = df.drop(['Unregistered Vehicle?', 'No Standing or Stopping Violation', 'Hydrant Violation', 'Double Parking Violation', \
                      'Issuer Precinct', 'Issuer Code', 'Issuer Command', 'Issuer Squad', 'Intersecting Street', 'Issuing Agency', \
                      'Law Section', 'Sub Division', 'Violation Legal Code', 'Violation Precinct', 'Violation Description', \
                      'Feet From Curb', 'Meter Number', 'To Hours In Effect', 'From Hours In Effect', \
                      'Violation Legal Code', 'Sub Division', 'Violation County', 'Violation In Front Of Or Opposite', 'House Number', \
                      'Violation Post Code', 'Time First Observed', 'Date First Observed', 'Street Code1', 'Street Code2', 'Street Code3',\
                      'Plate ID', 'Summons Number', 'Issue Date', 'Days Parking In Effect    '], axis = 1)

In [6]:
dropped_df.head(10)

,Registration State,Plate Type,Violation Code,Vehicle Body Type,Vehicle Make,Vehicle Expiration Date,Violation Location,Violation Time,Street Name,Vehicle Color,Vehicle Year
0,NY,PAS,67,SDN,TOYOT,20221210,10.0,1037A,W 28TH ST,BLK,2004
1,NY,PAS,51,SUBN,JEEP,20220908,10.0,1045A,27TH DR,GRAY,2017
2,NJ,PAS,63,SDN,JEEP,0,1.0,1116A,SOUTH ST,GRAY,0
3,NY,PAS,63,SUBN,LEXUS,20230820,1.0,1052A,SOUTH ST,NaN,0
4,NJ,PAS,63,SDN,HYUND,0,1.0,1107A,SOUTH ST,BLUE,0
5,NJ,PAS,63,NaN,JEEP,0,1.0,1050A,SOUTH ST,NaN,0
6,NJ,PAS,63,NaN,HYUND,0,1.0,1101A,SOUTH ST,BLUE,0
7,NY,PAS,67,SUBN,TOYOT,20230120,5.0,1205P,COLEMAN PLAYGROUND,WHITE,2021
8,NY,PAS,98,SUBN,NISSA,20230121,10.0,0535P,S/S W 28TH STREET,BLK,2002
9,NJ,PAS,10,SUBN,JEEP,0,6.0,0307P,WASHINGTON SQ SO,RED,0

In [7]:
dropped_df.dtypes

Registration State          object
Plate Type                  object
Violation Code               int64
Vehicle Body Type           object
Vehicle Make                object
Vehicle Expiration Date      int64
Violation Location         float64
Violation Time              object
Street Name                 object
Vehicle Color               object
Vehicle Year                 int64
dtype: object

In [8]:
dropped_df = dropped_df.dropna()

In [9]:
dropped_df['Plate Type'].count()

5388336

In [13]:
dropped_df.to_csv('Resources/cleaned_data.csv', index = True)